version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: shastacn_WPZH0
      WORDPRESS_CONFIG_EXTRA: |
        # define('WP_DEBUG', true);
        define('WP_HOME', 'http://localhost:8080');
        define('WP_SITEURL', 'http://localhost:8080');
        define('FORCE_SSL_LOGIN', false);
        define('FORCE_SSL_ADMIN', false);
        $$table_prefix  = '_ZH0_';
    volumes:
      - ./wp-content:/var/www/html/wp-content:delegated

  db:
    image: mariadb:10.4.11-bionic
    restart: always
    ports:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: shastacn_WPZH0
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql:delegated
      - "./containers/mysql/initdb.d/:/docker-entrypoint-initdb.d/"

volumes:
  db:
