version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wp-content:/var/www/html/wp-content:delegated
      - ./wp-config.php:/var/www/html/wp-config.php

  db:
    image: mariadb:10.4.11-bionic
    restart: always
    ports:
      - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: shastacn_WPZH0
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db:/var/lib/mysql:delegated
      - "./containers/mysql/initdb.d/:/docker-entrypoint-initdb.d/"

volumes:
  db:
